// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raftpb.proto

#ifndef PROTOBUF_raftpb_2eproto__INCLUDED
#define PROTOBUF_raftpb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_raftpb_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsConfStateImpl();
void InitDefaultsConfState();
void InitDefaultsEntryImpl();
void InitDefaultsEntry();
void InitDefaultsSnapshotMetadataImpl();
void InitDefaultsSnapshotMetadata();
void InitDefaultsSnapshotImpl();
void InitDefaultsSnapshot();
void InitDefaultsHardStateImpl();
void InitDefaultsHardState();
void InitDefaultsStorageImpl();
void InitDefaultsStorage();
void InitDefaultsMessageImpl();
void InitDefaultsMessage();
inline void InitDefaults() {
  InitDefaultsConfState();
  InitDefaultsEntry();
  InitDefaultsSnapshotMetadata();
  InitDefaultsSnapshot();
  InitDefaultsHardState();
  InitDefaultsStorage();
  InitDefaultsMessage();
}
}  // namespace protobuf_raftpb_2eproto
namespace raftpb {
class ConfState;
class ConfStateDefaultTypeInternal;
extern ConfStateDefaultTypeInternal _ConfState_default_instance_;
class Entry;
class EntryDefaultTypeInternal;
extern EntryDefaultTypeInternal _Entry_default_instance_;
class HardState;
class HardStateDefaultTypeInternal;
extern HardStateDefaultTypeInternal _HardState_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Snapshot;
class SnapshotDefaultTypeInternal;
extern SnapshotDefaultTypeInternal _Snapshot_default_instance_;
class SnapshotMetadata;
class SnapshotMetadataDefaultTypeInternal;
extern SnapshotMetadataDefaultTypeInternal _SnapshotMetadata_default_instance_;
class Storage;
class StorageDefaultTypeInternal;
extern StorageDefaultTypeInternal _Storage_default_instance_;
}  // namespace raftpb
namespace raftpb {

enum EntryType {
  EntryTrival = 0,
  EntryNormal = 1,
  EntryConfChange = 2,
  EntryType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  EntryType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool EntryType_IsValid(int value);
const EntryType EntryType_MIN = EntryTrival;
const EntryType EntryType_MAX = EntryConfChange;
const int EntryType_ARRAYSIZE = EntryType_MAX + 1;

const ::google::protobuf::EnumDescriptor* EntryType_descriptor();
inline const ::std::string& EntryType_Name(EntryType value) {
  return ::google::protobuf::internal::NameOfEnum(
    EntryType_descriptor(), value);
}
inline bool EntryType_Parse(
    const ::std::string& name, EntryType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EntryType>(
    EntryType_descriptor(), name, value);
}
enum MessageType {
  MsgTrival = 0,
  MsgHeartbeat = 1,
  MsgHeartbeatResp = 2,
  MsgVote = 3,
  MsgVoteResp = 4,
  MsgApp = 5,
  MsgAppResp = 6,
  MsgHup = 7,
  MsgCheckQuorum = 8,
  MsgTransferLeader = 9,
  MsgSnap = 10,
  MsgNode = 11,
  MsgNodeResp = 12,
  MsgBeat = 13,
  MsgProp = 14,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = MsgTrival;
const MessageType MessageType_MAX = MsgProp;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class ConfState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftpb.ConfState) */ {
 public:
  ConfState();
  virtual ~ConfState();

  ConfState(const ConfState& from);

  inline ConfState& operator=(const ConfState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConfState(ConfState&& from) noexcept
    : ConfState() {
    *this = ::std::move(from);
  }

  inline ConfState& operator=(ConfState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConfState* internal_default_instance() {
    return reinterpret_cast<const ConfState*>(
               &_ConfState_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ConfState* other);
  friend void swap(ConfState& a, ConfState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConfState* New() const PROTOBUF_FINAL { return New(NULL); }

  ConfState* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConfState& from);
  void MergeFrom(const ConfState& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConfState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 nodes = 1;
  int nodes_size() const;
  void clear_nodes();
  static const int kNodesFieldNumber = 1;
  ::google::protobuf::uint64 nodes(int index) const;
  void set_nodes(int index, ::google::protobuf::uint64 value);
  void add_nodes(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      nodes() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_nodes();

  // repeated uint64 learners = 2;
  int learners_size() const;
  void clear_learners();
  static const int kLearnersFieldNumber = 2;
  ::google::protobuf::uint64 learners(int index) const;
  void set_learners(int index, ::google::protobuf::uint64 value);
  void add_learners(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      learners() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_learners();

  // @@protoc_insertion_point(class_scope:raftpb.ConfState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > nodes_;
  mutable int _nodes_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > learners_;
  mutable int _learners_cached_byte_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_raftpb_2eproto::TableStruct;
  friend void ::protobuf_raftpb_2eproto::InitDefaultsConfStateImpl();
};
// -------------------------------------------------------------------

class Entry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftpb.Entry) */ {
 public:
  Entry();
  virtual ~Entry();

  Entry(const Entry& from);

  inline Entry& operator=(const Entry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Entry(Entry&& from) noexcept
    : Entry() {
    *this = ::std::move(from);
  }

  inline Entry& operator=(Entry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Entry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Entry* internal_default_instance() {
    return reinterpret_cast<const Entry*>(
               &_Entry_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Entry* other);
  friend void swap(Entry& a, Entry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Entry* New() const PROTOBUF_FINAL { return New(NULL); }

  Entry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Entry& from);
  void MergeFrom(const Entry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Entry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes Data = 4;
  void clear_data();
  static const int kDataFieldNumber = 4;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // uint64 Term = 2;
  void clear_term();
  static const int kTermFieldNumber = 2;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 Index = 3;
  void clear_index();
  static const int kIndexFieldNumber = 3;
  ::google::protobuf::uint64 index() const;
  void set_index(::google::protobuf::uint64 value);

  // .raftpb.EntryType Type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::raftpb::EntryType type() const;
  void set_type(::raftpb::EntryType value);

  // @@protoc_insertion_point(class_scope:raftpb.Entry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 index_;
  int type_;
  mutable int _cached_size_;
  friend struct ::protobuf_raftpb_2eproto::TableStruct;
  friend void ::protobuf_raftpb_2eproto::InitDefaultsEntryImpl();
};
// -------------------------------------------------------------------

class SnapshotMetadata : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftpb.SnapshotMetadata) */ {
 public:
  SnapshotMetadata();
  virtual ~SnapshotMetadata();

  SnapshotMetadata(const SnapshotMetadata& from);

  inline SnapshotMetadata& operator=(const SnapshotMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SnapshotMetadata(SnapshotMetadata&& from) noexcept
    : SnapshotMetadata() {
    *this = ::std::move(from);
  }

  inline SnapshotMetadata& operator=(SnapshotMetadata&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SnapshotMetadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SnapshotMetadata* internal_default_instance() {
    return reinterpret_cast<const SnapshotMetadata*>(
               &_SnapshotMetadata_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(SnapshotMetadata* other);
  friend void swap(SnapshotMetadata& a, SnapshotMetadata& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SnapshotMetadata* New() const PROTOBUF_FINAL { return New(NULL); }

  SnapshotMetadata* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SnapshotMetadata& from);
  void MergeFrom(const SnapshotMetadata& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SnapshotMetadata* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .raftpb.ConfState conf_state = 1;
  bool has_conf_state() const;
  void clear_conf_state();
  static const int kConfStateFieldNumber = 1;
  const ::raftpb::ConfState& conf_state() const;
  ::raftpb::ConfState* release_conf_state();
  ::raftpb::ConfState* mutable_conf_state();
  void set_allocated_conf_state(::raftpb::ConfState* conf_state);

  // uint64 index = 2;
  void clear_index();
  static const int kIndexFieldNumber = 2;
  ::google::protobuf::uint64 index() const;
  void set_index(::google::protobuf::uint64 value);

  // uint64 term = 3;
  void clear_term();
  static const int kTermFieldNumber = 3;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:raftpb.SnapshotMetadata)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::raftpb::ConfState* conf_state_;
  ::google::protobuf::uint64 index_;
  ::google::protobuf::uint64 term_;
  mutable int _cached_size_;
  friend struct ::protobuf_raftpb_2eproto::TableStruct;
  friend void ::protobuf_raftpb_2eproto::InitDefaultsSnapshotMetadataImpl();
};
// -------------------------------------------------------------------

class Snapshot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftpb.Snapshot) */ {
 public:
  Snapshot();
  virtual ~Snapshot();

  Snapshot(const Snapshot& from);

  inline Snapshot& operator=(const Snapshot& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Snapshot(Snapshot&& from) noexcept
    : Snapshot() {
    *this = ::std::move(from);
  }

  inline Snapshot& operator=(Snapshot&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Snapshot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Snapshot* internal_default_instance() {
    return reinterpret_cast<const Snapshot*>(
               &_Snapshot_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Snapshot* other);
  friend void swap(Snapshot& a, Snapshot& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Snapshot* New() const PROTOBUF_FINAL { return New(NULL); }

  Snapshot* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Snapshot& from);
  void MergeFrom(const Snapshot& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Snapshot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 1;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // .raftpb.SnapshotMetadata metadata = 2;
  bool has_metadata() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 2;
  const ::raftpb::SnapshotMetadata& metadata() const;
  ::raftpb::SnapshotMetadata* release_metadata();
  ::raftpb::SnapshotMetadata* mutable_metadata();
  void set_allocated_metadata(::raftpb::SnapshotMetadata* metadata);

  // @@protoc_insertion_point(class_scope:raftpb.Snapshot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::raftpb::SnapshotMetadata* metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_raftpb_2eproto::TableStruct;
  friend void ::protobuf_raftpb_2eproto::InitDefaultsSnapshotImpl();
};
// -------------------------------------------------------------------

class HardState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftpb.HardState) */ {
 public:
  HardState();
  virtual ~HardState();

  HardState(const HardState& from);

  inline HardState& operator=(const HardState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HardState(HardState&& from) noexcept
    : HardState() {
    *this = ::std::move(from);
  }

  inline HardState& operator=(HardState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HardState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HardState* internal_default_instance() {
    return reinterpret_cast<const HardState*>(
               &_HardState_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(HardState* other);
  friend void swap(HardState& a, HardState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HardState* New() const PROTOBUF_FINAL { return New(NULL); }

  HardState* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HardState& from);
  void MergeFrom(const HardState& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HardState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 vote = 2;
  void clear_vote();
  static const int kVoteFieldNumber = 2;
  ::google::protobuf::uint64 vote() const;
  void set_vote(::google::protobuf::uint64 value);

  // uint64 commit = 3;
  void clear_commit();
  static const int kCommitFieldNumber = 3;
  ::google::protobuf::uint64 commit() const;
  void set_commit(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:raftpb.HardState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 vote_;
  ::google::protobuf::uint64 commit_;
  mutable int _cached_size_;
  friend struct ::protobuf_raftpb_2eproto::TableStruct;
  friend void ::protobuf_raftpb_2eproto::InitDefaultsHardStateImpl();
};
// -------------------------------------------------------------------

class Storage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftpb.Storage) */ {
 public:
  Storage();
  virtual ~Storage();

  Storage(const Storage& from);

  inline Storage& operator=(const Storage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Storage(Storage&& from) noexcept
    : Storage() {
    *this = ::std::move(from);
  }

  inline Storage& operator=(Storage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Storage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Storage* internal_default_instance() {
    return reinterpret_cast<const Storage*>(
               &_Storage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(Storage* other);
  friend void swap(Storage& a, Storage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Storage* New() const PROTOBUF_FINAL { return New(NULL); }

  Storage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Storage& from);
  void MergeFrom(const Storage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Storage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .raftpb.Entry entries = 3;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 3;
  const ::raftpb::Entry& entries(int index) const;
  ::raftpb::Entry* mutable_entries(int index);
  ::raftpb::Entry* add_entries();
  ::google::protobuf::RepeatedPtrField< ::raftpb::Entry >*
      mutable_entries();
  const ::google::protobuf::RepeatedPtrField< ::raftpb::Entry >&
      entries() const;

  // .raftpb.Snapshot snap = 2;
  bool has_snap() const;
  void clear_snap();
  static const int kSnapFieldNumber = 2;
  const ::raftpb::Snapshot& snap() const;
  ::raftpb::Snapshot* release_snap();
  ::raftpb::Snapshot* mutable_snap();
  void set_allocated_snap(::raftpb::Snapshot* snap);

  // .raftpb.HardState hardstate = 4;
  bool has_hardstate() const;
  void clear_hardstate();
  static const int kHardstateFieldNumber = 4;
  const ::raftpb::HardState& hardstate() const;
  ::raftpb::HardState* release_hardstate();
  ::raftpb::HardState* mutable_hardstate();
  void set_allocated_hardstate(::raftpb::HardState* hardstate);

  // uint64 offset = 1;
  void clear_offset();
  static const int kOffsetFieldNumber = 1;
  ::google::protobuf::uint64 offset() const;
  void set_offset(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:raftpb.Storage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::raftpb::Entry > entries_;
  ::raftpb::Snapshot* snap_;
  ::raftpb::HardState* hardstate_;
  ::google::protobuf::uint64 offset_;
  mutable int _cached_size_;
  friend struct ::protobuf_raftpb_2eproto::TableStruct;
  friend void ::protobuf_raftpb_2eproto::InitDefaultsStorageImpl();
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftpb.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(Message* other);
  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .raftpb.Entry entries = 7;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 7;
  const ::raftpb::Entry& entries(int index) const;
  ::raftpb::Entry* mutable_entries(int index);
  ::raftpb::Entry* add_entries();
  ::google::protobuf::RepeatedPtrField< ::raftpb::Entry >*
      mutable_entries();
  const ::google::protobuf::RepeatedPtrField< ::raftpb::Entry >&
      entries() const;

  // bytes context = 12;
  void clear_context();
  static const int kContextFieldNumber = 12;
  const ::std::string& context() const;
  void set_context(const ::std::string& value);
  #if LANG_CXX11
  void set_context(::std::string&& value);
  #endif
  void set_context(const char* value);
  void set_context(const void* value, size_t size);
  ::std::string* mutable_context();
  ::std::string* release_context();
  void set_allocated_context(::std::string* context);

  // .raftpb.Snapshot snapshot = 9;
  bool has_snapshot() const;
  void clear_snapshot();
  static const int kSnapshotFieldNumber = 9;
  const ::raftpb::Snapshot& snapshot() const;
  ::raftpb::Snapshot* release_snapshot();
  ::raftpb::Snapshot* mutable_snapshot();
  void set_allocated_snapshot(::raftpb::Snapshot* snapshot);

  // uint64 to = 2;
  void clear_to();
  static const int kToFieldNumber = 2;
  ::google::protobuf::uint64 to() const;
  void set_to(::google::protobuf::uint64 value);

  // uint64 from = 3;
  void clear_from();
  static const int kFromFieldNumber = 3;
  ::google::protobuf::uint64 from() const;
  void set_from(::google::protobuf::uint64 value);

  // uint64 term = 4;
  void clear_term();
  static const int kTermFieldNumber = 4;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 logTerm = 5;
  void clear_logterm();
  static const int kLogTermFieldNumber = 5;
  ::google::protobuf::uint64 logterm() const;
  void set_logterm(::google::protobuf::uint64 value);

  // .raftpb.MessageType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::raftpb::MessageType type() const;
  void set_type(::raftpb::MessageType value);

  // bool reject = 10;
  void clear_reject();
  static const int kRejectFieldNumber = 10;
  bool reject() const;
  void set_reject(bool value);

  // uint64 index = 6;
  void clear_index();
  static const int kIndexFieldNumber = 6;
  ::google::protobuf::uint64 index() const;
  void set_index(::google::protobuf::uint64 value);

  // uint64 commit = 8;
  void clear_commit();
  static const int kCommitFieldNumber = 8;
  ::google::protobuf::uint64 commit() const;
  void set_commit(::google::protobuf::uint64 value);

  // uint64 rejectHint = 11;
  void clear_rejecthint();
  static const int kRejectHintFieldNumber = 11;
  ::google::protobuf::uint64 rejecthint() const;
  void set_rejecthint(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:raftpb.Message)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::raftpb::Entry > entries_;
  ::google::protobuf::internal::ArenaStringPtr context_;
  ::raftpb::Snapshot* snapshot_;
  ::google::protobuf::uint64 to_;
  ::google::protobuf::uint64 from_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 logterm_;
  int type_;
  bool reject_;
  ::google::protobuf::uint64 index_;
  ::google::protobuf::uint64 commit_;
  ::google::protobuf::uint64 rejecthint_;
  mutable int _cached_size_;
  friend struct ::protobuf_raftpb_2eproto::TableStruct;
  friend void ::protobuf_raftpb_2eproto::InitDefaultsMessageImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConfState

// repeated uint64 nodes = 1;
inline int ConfState::nodes_size() const {
  return nodes_.size();
}
inline void ConfState::clear_nodes() {
  nodes_.Clear();
}
inline ::google::protobuf::uint64 ConfState::nodes(int index) const {
  // @@protoc_insertion_point(field_get:raftpb.ConfState.nodes)
  return nodes_.Get(index);
}
inline void ConfState::set_nodes(int index, ::google::protobuf::uint64 value) {
  nodes_.Set(index, value);
  // @@protoc_insertion_point(field_set:raftpb.ConfState.nodes)
}
inline void ConfState::add_nodes(::google::protobuf::uint64 value) {
  nodes_.Add(value);
  // @@protoc_insertion_point(field_add:raftpb.ConfState.nodes)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ConfState::nodes() const {
  // @@protoc_insertion_point(field_list:raftpb.ConfState.nodes)
  return nodes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ConfState::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:raftpb.ConfState.nodes)
  return &nodes_;
}

// repeated uint64 learners = 2;
inline int ConfState::learners_size() const {
  return learners_.size();
}
inline void ConfState::clear_learners() {
  learners_.Clear();
}
inline ::google::protobuf::uint64 ConfState::learners(int index) const {
  // @@protoc_insertion_point(field_get:raftpb.ConfState.learners)
  return learners_.Get(index);
}
inline void ConfState::set_learners(int index, ::google::protobuf::uint64 value) {
  learners_.Set(index, value);
  // @@protoc_insertion_point(field_set:raftpb.ConfState.learners)
}
inline void ConfState::add_learners(::google::protobuf::uint64 value) {
  learners_.Add(value);
  // @@protoc_insertion_point(field_add:raftpb.ConfState.learners)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ConfState::learners() const {
  // @@protoc_insertion_point(field_list:raftpb.ConfState.learners)
  return learners_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ConfState::mutable_learners() {
  // @@protoc_insertion_point(field_mutable_list:raftpb.ConfState.learners)
  return &learners_;
}

// -------------------------------------------------------------------

// Entry

// .raftpb.EntryType Type = 1;
inline void Entry::clear_type() {
  type_ = 0;
}
inline ::raftpb::EntryType Entry::type() const {
  // @@protoc_insertion_point(field_get:raftpb.Entry.Type)
  return static_cast< ::raftpb::EntryType >(type_);
}
inline void Entry::set_type(::raftpb::EntryType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Entry.Type)
}

// uint64 Term = 2;
inline void Entry::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Entry::term() const {
  // @@protoc_insertion_point(field_get:raftpb.Entry.Term)
  return term_;
}
inline void Entry::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Entry.Term)
}

// uint64 Index = 3;
inline void Entry::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Entry::index() const {
  // @@protoc_insertion_point(field_get:raftpb.Entry.Index)
  return index_;
}
inline void Entry::set_index(::google::protobuf::uint64 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Entry.Index)
}

// bytes Data = 4;
inline void Entry::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Entry::data() const {
  // @@protoc_insertion_point(field_get:raftpb.Entry.Data)
  return data_.GetNoArena();
}
inline void Entry::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raftpb.Entry.Data)
}
#if LANG_CXX11
inline void Entry::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raftpb.Entry.Data)
}
#endif
inline void Entry::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raftpb.Entry.Data)
}
inline void Entry::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raftpb.Entry.Data)
}
inline ::std::string* Entry::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:raftpb.Entry.Data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Entry::release_data() {
  // @@protoc_insertion_point(field_release:raftpb.Entry.Data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Entry::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:raftpb.Entry.Data)
}

// -------------------------------------------------------------------

// SnapshotMetadata

// .raftpb.ConfState conf_state = 1;
inline bool SnapshotMetadata::has_conf_state() const {
  return this != internal_default_instance() && conf_state_ != NULL;
}
inline void SnapshotMetadata::clear_conf_state() {
  if (GetArenaNoVirtual() == NULL && conf_state_ != NULL) {
    delete conf_state_;
  }
  conf_state_ = NULL;
}
inline const ::raftpb::ConfState& SnapshotMetadata::conf_state() const {
  const ::raftpb::ConfState* p = conf_state_;
  // @@protoc_insertion_point(field_get:raftpb.SnapshotMetadata.conf_state)
  return p != NULL ? *p : *reinterpret_cast<const ::raftpb::ConfState*>(
      &::raftpb::_ConfState_default_instance_);
}
inline ::raftpb::ConfState* SnapshotMetadata::release_conf_state() {
  // @@protoc_insertion_point(field_release:raftpb.SnapshotMetadata.conf_state)
  
  ::raftpb::ConfState* temp = conf_state_;
  conf_state_ = NULL;
  return temp;
}
inline ::raftpb::ConfState* SnapshotMetadata::mutable_conf_state() {
  
  if (conf_state_ == NULL) {
    conf_state_ = new ::raftpb::ConfState;
  }
  // @@protoc_insertion_point(field_mutable:raftpb.SnapshotMetadata.conf_state)
  return conf_state_;
}
inline void SnapshotMetadata::set_allocated_conf_state(::raftpb::ConfState* conf_state) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete conf_state_;
  }
  if (conf_state) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      conf_state = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, conf_state, submessage_arena);
    }
    
  } else {
    
  }
  conf_state_ = conf_state;
  // @@protoc_insertion_point(field_set_allocated:raftpb.SnapshotMetadata.conf_state)
}

// uint64 index = 2;
inline void SnapshotMetadata::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SnapshotMetadata::index() const {
  // @@protoc_insertion_point(field_get:raftpb.SnapshotMetadata.index)
  return index_;
}
inline void SnapshotMetadata::set_index(::google::protobuf::uint64 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:raftpb.SnapshotMetadata.index)
}

// uint64 term = 3;
inline void SnapshotMetadata::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SnapshotMetadata::term() const {
  // @@protoc_insertion_point(field_get:raftpb.SnapshotMetadata.term)
  return term_;
}
inline void SnapshotMetadata::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftpb.SnapshotMetadata.term)
}

// -------------------------------------------------------------------

// Snapshot

// bytes data = 1;
inline void Snapshot::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Snapshot::data() const {
  // @@protoc_insertion_point(field_get:raftpb.Snapshot.data)
  return data_.GetNoArena();
}
inline void Snapshot::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raftpb.Snapshot.data)
}
#if LANG_CXX11
inline void Snapshot::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raftpb.Snapshot.data)
}
#endif
inline void Snapshot::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raftpb.Snapshot.data)
}
inline void Snapshot::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raftpb.Snapshot.data)
}
inline ::std::string* Snapshot::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:raftpb.Snapshot.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Snapshot::release_data() {
  // @@protoc_insertion_point(field_release:raftpb.Snapshot.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Snapshot::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:raftpb.Snapshot.data)
}

// .raftpb.SnapshotMetadata metadata = 2;
inline bool Snapshot::has_metadata() const {
  return this != internal_default_instance() && metadata_ != NULL;
}
inline void Snapshot::clear_metadata() {
  if (GetArenaNoVirtual() == NULL && metadata_ != NULL) {
    delete metadata_;
  }
  metadata_ = NULL;
}
inline const ::raftpb::SnapshotMetadata& Snapshot::metadata() const {
  const ::raftpb::SnapshotMetadata* p = metadata_;
  // @@protoc_insertion_point(field_get:raftpb.Snapshot.metadata)
  return p != NULL ? *p : *reinterpret_cast<const ::raftpb::SnapshotMetadata*>(
      &::raftpb::_SnapshotMetadata_default_instance_);
}
inline ::raftpb::SnapshotMetadata* Snapshot::release_metadata() {
  // @@protoc_insertion_point(field_release:raftpb.Snapshot.metadata)
  
  ::raftpb::SnapshotMetadata* temp = metadata_;
  metadata_ = NULL;
  return temp;
}
inline ::raftpb::SnapshotMetadata* Snapshot::mutable_metadata() {
  
  if (metadata_ == NULL) {
    metadata_ = new ::raftpb::SnapshotMetadata;
  }
  // @@protoc_insertion_point(field_mutable:raftpb.Snapshot.metadata)
  return metadata_;
}
inline void Snapshot::set_allocated_metadata(::raftpb::SnapshotMetadata* metadata) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete metadata_;
  }
  if (metadata) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      metadata = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, metadata, submessage_arena);
    }
    
  } else {
    
  }
  metadata_ = metadata;
  // @@protoc_insertion_point(field_set_allocated:raftpb.Snapshot.metadata)
}

// -------------------------------------------------------------------

// HardState

// uint64 term = 1;
inline void HardState::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 HardState::term() const {
  // @@protoc_insertion_point(field_get:raftpb.HardState.term)
  return term_;
}
inline void HardState::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftpb.HardState.term)
}

// uint64 vote = 2;
inline void HardState::clear_vote() {
  vote_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 HardState::vote() const {
  // @@protoc_insertion_point(field_get:raftpb.HardState.vote)
  return vote_;
}
inline void HardState::set_vote(::google::protobuf::uint64 value) {
  
  vote_ = value;
  // @@protoc_insertion_point(field_set:raftpb.HardState.vote)
}

// uint64 commit = 3;
inline void HardState::clear_commit() {
  commit_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 HardState::commit() const {
  // @@protoc_insertion_point(field_get:raftpb.HardState.commit)
  return commit_;
}
inline void HardState::set_commit(::google::protobuf::uint64 value) {
  
  commit_ = value;
  // @@protoc_insertion_point(field_set:raftpb.HardState.commit)
}

// -------------------------------------------------------------------

// Storage

// uint64 offset = 1;
inline void Storage::clear_offset() {
  offset_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Storage::offset() const {
  // @@protoc_insertion_point(field_get:raftpb.Storage.offset)
  return offset_;
}
inline void Storage::set_offset(::google::protobuf::uint64 value) {
  
  offset_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Storage.offset)
}

// .raftpb.Snapshot snap = 2;
inline bool Storage::has_snap() const {
  return this != internal_default_instance() && snap_ != NULL;
}
inline void Storage::clear_snap() {
  if (GetArenaNoVirtual() == NULL && snap_ != NULL) {
    delete snap_;
  }
  snap_ = NULL;
}
inline const ::raftpb::Snapshot& Storage::snap() const {
  const ::raftpb::Snapshot* p = snap_;
  // @@protoc_insertion_point(field_get:raftpb.Storage.snap)
  return p != NULL ? *p : *reinterpret_cast<const ::raftpb::Snapshot*>(
      &::raftpb::_Snapshot_default_instance_);
}
inline ::raftpb::Snapshot* Storage::release_snap() {
  // @@protoc_insertion_point(field_release:raftpb.Storage.snap)
  
  ::raftpb::Snapshot* temp = snap_;
  snap_ = NULL;
  return temp;
}
inline ::raftpb::Snapshot* Storage::mutable_snap() {
  
  if (snap_ == NULL) {
    snap_ = new ::raftpb::Snapshot;
  }
  // @@protoc_insertion_point(field_mutable:raftpb.Storage.snap)
  return snap_;
}
inline void Storage::set_allocated_snap(::raftpb::Snapshot* snap) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete snap_;
  }
  if (snap) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      snap = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, snap, submessage_arena);
    }
    
  } else {
    
  }
  snap_ = snap;
  // @@protoc_insertion_point(field_set_allocated:raftpb.Storage.snap)
}

// repeated .raftpb.Entry entries = 3;
inline int Storage::entries_size() const {
  return entries_.size();
}
inline void Storage::clear_entries() {
  entries_.Clear();
}
inline const ::raftpb::Entry& Storage::entries(int index) const {
  // @@protoc_insertion_point(field_get:raftpb.Storage.entries)
  return entries_.Get(index);
}
inline ::raftpb::Entry* Storage::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:raftpb.Storage.entries)
  return entries_.Mutable(index);
}
inline ::raftpb::Entry* Storage::add_entries() {
  // @@protoc_insertion_point(field_add:raftpb.Storage.entries)
  return entries_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::raftpb::Entry >*
Storage::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:raftpb.Storage.entries)
  return &entries_;
}
inline const ::google::protobuf::RepeatedPtrField< ::raftpb::Entry >&
Storage::entries() const {
  // @@protoc_insertion_point(field_list:raftpb.Storage.entries)
  return entries_;
}

// .raftpb.HardState hardstate = 4;
inline bool Storage::has_hardstate() const {
  return this != internal_default_instance() && hardstate_ != NULL;
}
inline void Storage::clear_hardstate() {
  if (GetArenaNoVirtual() == NULL && hardstate_ != NULL) {
    delete hardstate_;
  }
  hardstate_ = NULL;
}
inline const ::raftpb::HardState& Storage::hardstate() const {
  const ::raftpb::HardState* p = hardstate_;
  // @@protoc_insertion_point(field_get:raftpb.Storage.hardstate)
  return p != NULL ? *p : *reinterpret_cast<const ::raftpb::HardState*>(
      &::raftpb::_HardState_default_instance_);
}
inline ::raftpb::HardState* Storage::release_hardstate() {
  // @@protoc_insertion_point(field_release:raftpb.Storage.hardstate)
  
  ::raftpb::HardState* temp = hardstate_;
  hardstate_ = NULL;
  return temp;
}
inline ::raftpb::HardState* Storage::mutable_hardstate() {
  
  if (hardstate_ == NULL) {
    hardstate_ = new ::raftpb::HardState;
  }
  // @@protoc_insertion_point(field_mutable:raftpb.Storage.hardstate)
  return hardstate_;
}
inline void Storage::set_allocated_hardstate(::raftpb::HardState* hardstate) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete hardstate_;
  }
  if (hardstate) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      hardstate = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, hardstate, submessage_arena);
    }
    
  } else {
    
  }
  hardstate_ = hardstate;
  // @@protoc_insertion_point(field_set_allocated:raftpb.Storage.hardstate)
}

// -------------------------------------------------------------------

// Message

// .raftpb.MessageType type = 1;
inline void Message::clear_type() {
  type_ = 0;
}
inline ::raftpb::MessageType Message::type() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.type)
  return static_cast< ::raftpb::MessageType >(type_);
}
inline void Message::set_type(::raftpb::MessageType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.type)
}

// uint64 to = 2;
inline void Message::clear_to() {
  to_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::to() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.to)
  return to_;
}
inline void Message::set_to(::google::protobuf::uint64 value) {
  
  to_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.to)
}

// uint64 from = 3;
inline void Message::clear_from() {
  from_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::from() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.from)
  return from_;
}
inline void Message::set_from(::google::protobuf::uint64 value) {
  
  from_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.from)
}

// uint64 term = 4;
inline void Message::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::term() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.term)
  return term_;
}
inline void Message::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.term)
}

// uint64 logTerm = 5;
inline void Message::clear_logterm() {
  logterm_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::logterm() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.logTerm)
  return logterm_;
}
inline void Message::set_logterm(::google::protobuf::uint64 value) {
  
  logterm_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.logTerm)
}

// uint64 index = 6;
inline void Message::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::index() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.index)
  return index_;
}
inline void Message::set_index(::google::protobuf::uint64 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.index)
}

// repeated .raftpb.Entry entries = 7;
inline int Message::entries_size() const {
  return entries_.size();
}
inline void Message::clear_entries() {
  entries_.Clear();
}
inline const ::raftpb::Entry& Message::entries(int index) const {
  // @@protoc_insertion_point(field_get:raftpb.Message.entries)
  return entries_.Get(index);
}
inline ::raftpb::Entry* Message::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:raftpb.Message.entries)
  return entries_.Mutable(index);
}
inline ::raftpb::Entry* Message::add_entries() {
  // @@protoc_insertion_point(field_add:raftpb.Message.entries)
  return entries_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::raftpb::Entry >*
Message::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:raftpb.Message.entries)
  return &entries_;
}
inline const ::google::protobuf::RepeatedPtrField< ::raftpb::Entry >&
Message::entries() const {
  // @@protoc_insertion_point(field_list:raftpb.Message.entries)
  return entries_;
}

// uint64 commit = 8;
inline void Message::clear_commit() {
  commit_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::commit() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.commit)
  return commit_;
}
inline void Message::set_commit(::google::protobuf::uint64 value) {
  
  commit_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.commit)
}

// .raftpb.Snapshot snapshot = 9;
inline bool Message::has_snapshot() const {
  return this != internal_default_instance() && snapshot_ != NULL;
}
inline void Message::clear_snapshot() {
  if (GetArenaNoVirtual() == NULL && snapshot_ != NULL) {
    delete snapshot_;
  }
  snapshot_ = NULL;
}
inline const ::raftpb::Snapshot& Message::snapshot() const {
  const ::raftpb::Snapshot* p = snapshot_;
  // @@protoc_insertion_point(field_get:raftpb.Message.snapshot)
  return p != NULL ? *p : *reinterpret_cast<const ::raftpb::Snapshot*>(
      &::raftpb::_Snapshot_default_instance_);
}
inline ::raftpb::Snapshot* Message::release_snapshot() {
  // @@protoc_insertion_point(field_release:raftpb.Message.snapshot)
  
  ::raftpb::Snapshot* temp = snapshot_;
  snapshot_ = NULL;
  return temp;
}
inline ::raftpb::Snapshot* Message::mutable_snapshot() {
  
  if (snapshot_ == NULL) {
    snapshot_ = new ::raftpb::Snapshot;
  }
  // @@protoc_insertion_point(field_mutable:raftpb.Message.snapshot)
  return snapshot_;
}
inline void Message::set_allocated_snapshot(::raftpb::Snapshot* snapshot) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete snapshot_;
  }
  if (snapshot) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      snapshot = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, snapshot, submessage_arena);
    }
    
  } else {
    
  }
  snapshot_ = snapshot;
  // @@protoc_insertion_point(field_set_allocated:raftpb.Message.snapshot)
}

// bool reject = 10;
inline void Message::clear_reject() {
  reject_ = false;
}
inline bool Message::reject() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.reject)
  return reject_;
}
inline void Message::set_reject(bool value) {
  
  reject_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.reject)
}

// uint64 rejectHint = 11;
inline void Message::clear_rejecthint() {
  rejecthint_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::rejecthint() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.rejectHint)
  return rejecthint_;
}
inline void Message::set_rejecthint(::google::protobuf::uint64 value) {
  
  rejecthint_ = value;
  // @@protoc_insertion_point(field_set:raftpb.Message.rejectHint)
}

// bytes context = 12;
inline void Message::clear_context() {
  context_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message::context() const {
  // @@protoc_insertion_point(field_get:raftpb.Message.context)
  return context_.GetNoArena();
}
inline void Message::set_context(const ::std::string& value) {
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raftpb.Message.context)
}
#if LANG_CXX11
inline void Message::set_context(::std::string&& value) {
  
  context_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raftpb.Message.context)
}
#endif
inline void Message::set_context(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raftpb.Message.context)
}
inline void Message::set_context(const void* value, size_t size) {
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raftpb.Message.context)
}
inline ::std::string* Message::mutable_context() {
  
  // @@protoc_insertion_point(field_mutable:raftpb.Message.context)
  return context_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_context() {
  // @@protoc_insertion_point(field_release:raftpb.Message.context)
  
  return context_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_context(::std::string* context) {
  if (context != NULL) {
    
  } else {
    
  }
  context_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), context);
  // @@protoc_insertion_point(field_set_allocated:raftpb.Message.context)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace raftpb

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::raftpb::EntryType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::raftpb::EntryType>() {
  return ::raftpb::EntryType_descriptor();
}
template <> struct is_proto_enum< ::raftpb::MessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::raftpb::MessageType>() {
  return ::raftpb::MessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_raftpb_2eproto__INCLUDED
